# Generated by Django 3.0.6 on 2020-05-26 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hello_test',
            new_name='Test',
        ),
    ]
