# Generated by Django 3.0.6 on 2020-06-09 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20200608_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50, verbose_name='银行名称')),
                ('city', models.CharField(max_length=30, verbose_name='城市')),
                ('point', models.CharField(max_length=60, verbose_name='网点')),
            ],
            options={
                'verbose_name_plural': '银行卡',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(default='', max_length=30, verbose_name='卡号')),
                ('card_user', models.CharField(default='', max_length=10, verbose_name='姓名')),
                ('add_time', models.DateField(auto_now=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '银行卡账户_基本信息',
                'verbose_name_plural': '银行卡账户',
            },
        ),
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=30, verbose_name='卡号')),
                ('card_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Bank', verbose_name='选择银行')),
            ],
            options={
                'verbose_name_plural': '卡号信息',
            },
        ),
        migrations.CreateModel(
            name='CardDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(default='', max_length=30, verbose_name='电话')),
                ('mail', models.CharField(default='', max_length=30, verbose_name='邮箱')),
                ('city', models.CharField(default='', max_length=10, verbose_name='城市')),
                ('address', models.CharField(default='', max_length=30, verbose_name='详细地址')),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hello.Card', verbose_name='卡号')),
            ],
            options={
                'verbose_name': '账户_个人资料',
                'verbose_name_plural': '个人资料',
            },
        ),
    ]
