# Generated by Django 3.0.6 on 2020-06-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(default='', max_length=30, verbose_name='老师')),
                ('tel', models.CharField(default='', max_length=30, verbose_name='电话')),
                ('mial', models.CharField(default='', max_length=30, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '老师',
                'verbose_name_plural': '老师',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(to='hello.Teacher', verbose_name='老师'),
        ),
    ]
