# Generated by Django 3.0.6 on 2020-06-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_articleclassifty_articledetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], default='', max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='auth',
            field=models.CharField(blank=True, default='admin', max_length=10, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default='', verbose_name='年龄'),
        ),
    ]
