# Generated by Django 3.0.6 on 2020-06-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_auto_20200616_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='', max_length=30, verbose_name='学号'),
        ),
    ]
