# Generated by Django 3.0.6 on 2020-06-27 18:06

import datetime
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_fileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='名称')),
                ('image', stdimage.models.StdImageField(upload_to='path/to', verbose_name='传图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '传图片',
                'verbose_name_plural': '传图片',
            },
        ),
    ]
