# Generated by Django 3.0.6 on 2020-06-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_uploadimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherMan',
            fields=[
            ],
            options={
                'verbose_name': '男老师',
                'verbose_name_plural': '男老师',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hello.teacher',),
        ),
        migrations.AddField(
            model_name='teacher',
            name='sex',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], default='', max_length=10, null=True, verbose_name='性别'),
        ),
    ]
