# Generated by Django 3.0.6 on 2020-06-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0017_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='昵称')),
                ('sex', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=11, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, default='', verbose_name='年龄')),
                ('mail', models.EmailField(blank=True, default='', max_length=30)),
                ('create_time', models.DateField(auto_now=True, verbose_name='添加时间')),
            ],
        ),
    ]
