# Generated by Django 3.0.8 on 2020-07-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0018_userpersonalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
